### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by AlmasShahid**
Attempted task 1 - Triangle Type

### CODE REVIEW

**Comment by wadawe** [comment]
Looks good to me. We were in a Discord call for the Practical session and also worked on this task. I'll see if I can merge what you've done with what we made.

**Review by wadawe — APPROVED** [review]
LGTM

**Comment by AlmasShahid** [comment]
Ah okay. Sorry, wasn't aware of the Discord call, otherwise would have joined

**Comment by wadawe** [comment]
> Ah okay. Sorry, wasn't aware of the Discord call, otherwise would have joined

Yeah no problem. We probably should have pinged in the Discord chat channel. I just joined a VC and then Vijay & Varut joined me in it.

**Pull request merged**
